# https://www.playframework.com/documentation/latest/Configuration
play {
  # http.secret.key = "82c895a6fbf13e55896f2c53a8dba88a85acc1a026215c48e61e5b0f35d95241"
  # # http.secret.key = ${?APPLICATION_SECRET}

  jwt {
    secret = "82c895a6fbf13e55896f2c53a8dba88a85acc1a026215c48e61e5b0f35d95241"
    algorithm = "HS256"
    expireInSeconds = 3600
  }

  modules.enabled += "modules.ServiceModule"

  filters {
    enabled += "play.filters.cors.CORSFilter"
  }
  

  filters.cors {
    allowedOrigins = ["http://localhost:5173"]
    allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowedHttpHeaders = ["Accept", "Content-Type", "Authorization"]
  }
}

fixedConnectionPool = 20

database.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = ${fixedConnectionPool}
  }
}

slick.dbs.default {
  hikariCP.maximumPoolSize = ${fixedConnectionPool}
  hikariCP.minimumIdle = 5
  profile = "slick.jdbc.MySQLProfile$"
  db {
    driver = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://127.0.0.1:3306/scala_kafka?preserveInstants=true&serverTimezone=UTC"
    user = "rey"
    password = "rey"
    
    # Increase these pool configuration properties
    numThreads = 20        # Slick session thread pool size
    maxConnections = 20    # HikariCP maximum connection limit
    minConnections = 5     # HikariCP minimum idle connections
  }
}
